### ISSUE TITLE
Vector instruction decoding issue

### ISSUE THREAD

**Issue by taoliug** [riscv/riscv-ovpsim#34]
While testing random vector instruction based on vector spec 0.8 with upstream ovpsim, I encountered a few illegal instructions below:

**vadc.vvm   v24,v16,v30,v0**
Info 156: 'riscvOVPsim/cpu', 0x000000008000020a(_main+2): Machine 410f0c57 undef
Warning (RISCV_UDEC) CPU 'riscvOVPsim/cpu' 0x8000020a 410f0c57 undef: Undecoded instruction

**vasub.vx   v28,v10,s5**
Info 258: 'riscvOVPsim/cpu', 0x0000000080000212(_main+a): Machine 2eaaee57 undef
Warning (RISCV_UDEC) CPU 'riscvOVPsim/cpu' 0x80000212 2eaaee57 undef: Undecoded instruction

Can you take a look if this is expected?

**Comment by simon5656** [comment]
Can you please post the .S (and any includes/headers), the .log (with the trace options set as per riscv-dv for trace compare), and importantly - the riscvOVPsim.ic file that you are using to define the device being simulated. thanks.

**Comment by taoliug** [comment]
Assembly test (please rename it to .S)
[riscv_vector_arithmetic_test_0.txt](https://github.com/riscv/riscv-ovpsim/files/4017945/riscv_vector_arithmetic_test_0.txt)

Log:
[riscv_vector_arithmetic_test.0.log](https://github.com/riscv/riscv-ovpsim/files/4017950/riscv_vector_arithmetic_test.0.log)

OVPSIM CFG:
https://github.com/google/riscv-dv/blob/master/target/rv64gcv/riscvOVPsim.ic

**Comment by simon5656** [comment]
OK thanks - you need to be careful what you are simulating when it comes to vectors.
The vector specification changed a lot end of 2019 with many new instructions coming in, old instructions going out, and decodes changing. riscvOVPsim was updated on a weekly/daily basis to reflect this.
Your log showed running: v20190708.0 - which is way too old - please always use the latest.
Current release (riscvOVPsim.exe --version) 20191217.0 implements the full vectors 0.8.

In fact, if you look at the model pdf doc in this repo it describes all the different vector versions and changes - it will be kept up to date as vector spec changes - and there is a run time parameter to riscvOVPsim that allows selection of versions. Legal values of parameter vector_version are: 
```
    0.7.1-draft-20190605
    0.7.1-draft-20190605+
    0.8-draft-20190906
    0.8-draft-20191004
    0.8-draft-20191117
    0.8-draft-20191118
    0.8 
    master

```
So - a) please use latest release
and b) in your riscvOVPsim.ic please specify very carefully exactly the hardware spec you want - as the vector spec is very configurable and many instructions are polymorphic...

pls add
`--override riscvOVPsim/cpu/vector_version=0.8
`to your riscvOVPsim.ic control file.

and don't forget to set VLEN, ELEN, SLEN to configure the hardware vector engine.

**Comment by taoliug** [comment]
Thanks, the original decoding issue is gone, still have one decoding failure:

vwmaccsu.vv v16,v14,v18

Info 1611: 'riscvOVPsim/cpu', 0x000000008000150a(_main+12ba): Machine fe982357 undef
Warning (RISCV_UDEC) CPU 'riscvOVPsim/cpu' 0x8000150a fe982357 undef: Undecoded instruction

[vector_error.tar.gz](https://github.com/riscv/riscv-ovpsim/files/4021602/vector_error.tar.gz)

**Comment by simon5656** [comment]
pls post the riscvOVPsim.ic so we can reproduce what you did - without this control file we don't know what version of the vectors spec you are configured to run or the settings of the hardware for the vector engine - we need to reproduce exactly what you input - alternatively you could run riscvOVPsim.exe with --logfile <name> and post that logfile - as it lists all command line options in the log.

**Comment by taoliug** [comment]
https://github.com/google/riscv-dv/blob/master/target/rv64gcv/riscvOVPsim.ic

**Comment by duncangraham-Imperas** [comment]
We found the decode issue reported and have it fixed on our development version. Once this has passed through our regression test system, we will upload a new release. This is usually the next day.

**Comment by simon5656** [comment]
> https://github.com/google/riscv-dv/blob/master/target/rv64gcv/riscvOVPsim.ic

The simulator has defaults for 3 values that will be fixed by your hardware. You need to ensure you use these in your config files - so that the config of the simulated hardware vector engine is obvious and explicit.

pls add these to your config file:
```
--override riscvOVPsim/cpu/ELEN=64
--override riscvOVPsim/cpu/SLEN=64
--override riscvOVPsim/cpu/VLEN=512

```

**Comment by simon5656** [comment]
New release fixing this has been put in the repo. Closing this issue.
