### ISSUE TITLE
Run ovpsim in baremetal mode

### ISSUE THREAD

**Issue by taoliug** [riscv/riscv-ovpsim#37]
Currently if ecall/ebreak is executed, it's going to throw below error. Is it possible to let the trap handler(mtvec)  to handle it. 

Info 271: 'riscvOVPsim/cpu', 0x0000000080000440(main_21+1c0): Machine 9002     ebreak
Fatal (RISCV/PK) SYSCALL(unhandled(nr=-2147324292))
Info Exiting

Besides, can wfi be treated as nop in baremetal simulation?

**Comment by duncangraham-Imperas** [comment]
The default semihost library converts ebreak calls to the required system functionality on the host, for example output to stdout. This may be turned off using a parameter override.
You can get a list of all the parameter overrides by adding **--showoverrides** to the command line.
To turn off the default semihost library you should add
**--override riscvOVPsim/cpu/defaultdemihost=F**
NOTE: This will turn off **ALL** semihost support

In the same way the list of overrides will also provide you with the following which, when added to the command line, will cause the OVP RISC-V processor model to implement wfi as nop
**--override riscvOVPsim/cpu/wfi_as_nop=T**

**Comment by taoliug** [comment]
Thanks, it works with below override:
--override riscvOVPsim/cpu/defaultsemihost=F
--override riscvOVPsim/cpu/wfi_is_nop=T

One side effect I noticed is that the program execution cannot be terminated with an instruction with "_exit" label. How to properly terminate the test in this mode?

**Comment by duncangraham-Imperas** [comment]
Yes, trapping execution at the address of _exit and terminating the simulation is part of the functionality of the semihost library.
If you have a rough idea of how long the application takes to run you could terminate at some time after it completes using
**--override  riscvOVPsim/finishtime=<time in seconds>**
To be honest the simulator is fast enough so that as long as the time is longer than the application execution takes you shouldn't notice the extra instructions executed!

**Comment by taoliug** [comment]
Is it possible to still support the _exit label when semi hosting is turned off? We are running random programs with ovpsim, and the length of the program is not deterministic. The finish time needs to be set to a number that's big enough to work for all cases. This will result in huge log size for most of the tests.

**Comment by duncangraham-Imperas** [comment]
There are many configurable options but the semihost support is either on/off on this executable.

**Comment by duncangraham-Imperas** [comment]
We have extended riscvOVPsim to add the ability to specify a symbol or an address that when fetched will cause the simulation to terminate.
So you can now stop on _exit by specifying this as the symbol to stop execution on by adding   **-exitonsymbol _exit**
