### ISSUE TITLE
Error when defining more than 2 memories in the memory map

### ISSUE THREAD

**Issue by RiadhENIT** [riscv/riscv-ovpsim#39]
Hi,
I am trying to simulate a very simple C program on a target with four memories and a specific memory map. However, I get an error when defining more than two memories, whatever the order I define them. It seems as if the simulator was unable to load more than two memory regions.
I join my files to this message. Can you give my a clue?
Thanks

1 - compile the code with : ./compile.sh
2 - launch the sim with : ./riscvOVPsim.sh
[issue_prog.zip](https://github.com/riscv/riscv-ovpsim/files/4075863/issue_prog.zip)

**Comment by duncangraham-Imperas** [comment]
I found the rather silly mistake I made in the code :-(
This will be fixed and a new version uploaded asap.
