### ISSUE TITLE
Can't use riscv64-unknown-elf-gdb to debug dhrystone.RISCV32.elf

### ISSUE THREAD

**Issue by dthome9180** [riscv/riscv-ovpsim#4]
Hi, all

After run DEBUG_GDB_dhrystone.bat in cygwin enviroment, I want to test the gdb. So...
What's wrong I met?

Dong Tong

td@huawei-td /cygdrive/d/riscv/riscv-compliance/riscv-ovpsim/examples/dhrystone
$ riscv64-unknown-elf-gdb dhrystone.RISCV32.elf
GNU gdb (GDB) 8.2.90.20190228-git
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "--host=x86_64-w64-mingw32 --target=riscv64-unknown-elf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from dhrystone.RISCV32.elf...
(gdb) show arch
The target architecture is set automatically (currently riscv:rv32)
(gdb) target remote localhost 14705
localhost 14705: No such file or directory.
(gdb) target remote localhost:14705
Undefined command: "".  Try "help".
(gdb) target remote localhost:14705
Remote debugging using localhost:14705
Remote 'g' packet reply is too long (expected 132 bytes, got 260 bytes): 0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000b00001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

**Comment by eroom1966** [comment]
Hi Dong,

This simulator has a GDB console built in, you can try running the batch file directly to launch the GDB already connected to the target simulator

DEBUG_GDB_RV32_dhrystone.bat

I suspect that the version of GDB you are using is expecting a different G packet size - this is usually the case when a mismatch exists between the GDB Client and the GDB Server (the simulator)

Thx
Lee

**Comment by dthome9180** [comment]
I got it. When using ovpsim simulator, the ovpsim riscv-toolchain must be used. I download the current toolchain from www.ovpworld.org. It's working.

My issue is due to the wrong gdb used. This issue should be closed

Dong

**Comment by jstraus59** [comment]
Actually, it should be possible to use any toolchain with riscv ovpsim.

You may need to use the gdb that is provided in riscv-ovpsim in bin/<arch>/riscv-none-embed-gdb if the gdb in the toolchain you are using is incompatible with the gdb server built into riscv-ovpsim.

If you can provide info on where you got the gdb that had problems with riscv-ovpsim then we can look into that issue.

Thanks

Jim

**Comment by dthome9180** [comment]
Jim
Thanks your reply. the gdb used before was from SiFive Freedom Studio, rv64-unknown-elf-gcc. It can be downloaded from SiFive website freely. 

Anyway, I think the problem is the riscv-ovpsim from github.com/riscv/riscv-ovpsim maybe is different to the one from ovpworld.org. When I donwload ovpsim and tool-chain all from ovpworld.org, it work corretly.
 
Dong
