### ISSUE TITLE
Tag new releases

### ISSUE THREAD

**Issue by abhinay-kayastha** [riscv/riscv-ovpsim#44]
The README.md indicates the latest version to be: Date : 06 Feb 2020 Version: 20200206.0

However the "releases" page is still pointing to v20191217.0 as the latest release.

Could you add the tag v20200206.0 release?

**Comment by jstraus59** [comment]
We do not create a release for every commit. But any commit may be downloaded using the “clone or download” button. So if you would like the latest version just download it directly.

**Comment by mikeyangsiv** [comment]
What is the policy for generating a `release`?  Are the unreleased versions less stable?

**Comment by jstraus59** [comment]
Releases are typically made when Imperas makes its regular quarterly product releases or when a critical bug has been fixed in riscv-ovpsim.

**Comment by duncangraham-Imperas** [comment]
It was asked "Are the unreleased versions less stable?"
The quick answer is no, the unreleased versions are tested and verified to the same level as the released versions. As previously mentioned the releases are really tagging a version that is in synch with the Imperas regular product releases.
