### ISSUE TITLE
Re-compiling the CoreMark example

### ISSUE THREAD

**Issue by RiadhENIT** [riscv/riscv-ovpsim#46]
Hi,

I would like to re-compile the CoreMark example. In this objective, I have downloaded the necessary files from https://github.com/eembc/coremark and added the 32_core_portme.c and 32_core_portme.h, given in the example directory.
However, the compiler complains about the lack of a file called  simulatorIntercepts.h wich is not available. Can you tell me where is this file? Is it part of the whole OVPsim simulator? How to get it?

Thanks.

**Comment by duncangraham-Imperas** [comment]
The file simulatorIntercepts.h is included as part of an OVPsim or Imperas product install.
However, I think it was left in this file from a previous port that used a simulator intercepted function. impProcessorInstructions, to provide the instruction count, used to approximate current time. In the RISC-V case the CSR mcycle is used to obtain the instruction count so the simulator function is not used.

**Comment by RiadhENIT** [comment]
OK. Later, I managed to compile when commenting the corresponding #include, but was not sure of the consequences.
Thank you for this clarification.
