### ISSUE TITLE
decode data

### ISSUE THREAD

**Issue by weedmank** [riscv/riscv-ovpsim#49]
Why is there a "." instead of "0" shown for bit 3 in your https://github.com/riscv/riscv-ovpsim/blob/master/source/riscvDecode.c file.  There are other lines in this file that are done similarly.  riscv-spec.pdf p. 130 shows it needing to be 0 to decode for RV32I  R type ADD.
 DECODE32_ENTRY(          ADD_R, "|0000000|.....|.....|000|.....|011.011|"),

**Comment by duncangraham-Imperas** [comment]
My understanding, this is used to decode both the ADD and ADDW instructions which perform largely the same operation.
You can see this if you follow into the file riscvMorph.c and find the ADD_R in the dispatchTable[]. This uses the emitBinopRRR function to generate the morph code for the instructions behaviour.

**Comment by weedmank** [comment]
I kind of figured it was that, but ADDW is a 64 bit instruction and it seems a bit odd to be placed/associated with a DECODE32

Thanks

**Comment by duncangraham-Imperas** [comment]
It is not a 64-bit instruction, the RISC-V has 32-bit and 16-bit instructions, rather it is a 32-bit instruction that operates on 64-bit data.

**Comment by weedmank** [comment]
You’re correct.  I was think RV64i vs RV32i, not 32 bit decode.

p. 37 riscv-spec.pdf “ADDW and SUBW are RV64I-only instructions that are defined …”
